name: Deploy Products MFE

on:
  push:
    branches:
      - ci-test
    paths:
      - 'apps/products/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

jobs:
  deploy-products:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm --filter products build

      - name: Set credentials
        if: github.ref == 'refs/heads/main'
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION=${{vars.CLOUDFRONT_DISTRIBUTION}}" >> $GITHUB_ENV
          echo "BUCKET=s3://${{vars.S3_BUCKET}}/products" >> $GITHUB_ENV

      - name: Install dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pnpm run ci

      - name: Build products app
        run: |
          pnpm --filter @aurex/products run build

      - name: Upload to S3
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" 
          aws configure set default.region "$REGION"
          ...
          cd apps/products/
          aws s3 sync --cache-control 'max-age=604800' --exclude index.html --exclude remoteEntry.js ./dist/ "$BUCKET"
          aws s3 sync --cache-control 'no-cache' ./dist/ "$BUCKET"

      - name: Invalidate Cloudfront cache
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region "$REGION"
          aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION" --paths "/products/*"
